default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: labsdb_development
  username: postgres
  password: password

test:
  <<: *default
  database: labsdb_test
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: labsdb_production
  username: labsdb
